CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE,name TEXT NOT NULL,password TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS organizations(id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,name TEXT NOT NULL,accent TEXT NOT NULL DEFAULT '#253951',domains TEXT NOT NULL DEFAULT '[]',stripe_account TEXT,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS memberships(user_id TEXT REFERENCES users(id),org_id TEXT REFERENCES organizations(id),role TEXT NOT NULL,PRIMARY KEY(user_id,org_id));
CREATE TABLE IF NOT EXISTS sessions(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS tokens(id TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),token TEXT NOT NULL UNIQUE,label TEXT NOT NULL,scopes TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS invites(token TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),email TEXT NOT NULL,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS resets(token TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS assets(id TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),name TEXT NOT NULL,mime TEXT NOT NULL,bytes BYTEA NOT NULL,meta TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products(id TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),name TEXT NOT NULL,niche TEXT NOT NULL,mode TEXT NOT NULL DEFAULT 'quote',draft TEXT NOT NULL,revision BIGINT NOT NULL DEFAULT 1,published BIGINT,active BIGINT NOT NULL DEFAULT 0,created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS versions(product_id TEXT REFERENCES products(id),revision BIGINT NOT NULL,org_id TEXT REFERENCES organizations(id),manifest TEXT NOT NULL,created TEXT NOT NULL,PRIMARY KEY(product_id,revision));
CREATE TABLE IF NOT EXISTS configurations(id TEXT PRIMARY KEY,user_id TEXT REFERENCES users(id),org_id TEXT REFERENCES organizations(id),product_id TEXT REFERENCES products(id),version BIGINT NOT NULL,name TEXT NOT NULL,selection TEXT NOT NULL,manifest TEXT NOT NULL,amount BIGINT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders(id TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),user_id TEXT REFERENCES users(id),configuration_id TEXT REFERENCES configurations(id),status TEXT NOT NULL,amount BIGINT NOT NULL,offer_revision BIGINT NOT NULL DEFAULT 0,offer_note TEXT NOT NULL DEFAULT '',checkout_id TEXT UNIQUE,checkout_url TEXT,payment_intent TEXT,created TEXT NOT NULL,updated TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS messages(id TEXT PRIMARY KEY,order_id TEXT REFERENCES orders(id),user_id TEXT REFERENCES users(id),body TEXT NOT NULL,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS events(id TEXT PRIMARY KEY,created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS generations(id TEXT PRIMARY KEY,org_id TEXT REFERENCES organizations(id),request_key TEXT NOT NULL,provider_id TEXT,status TEXT NOT NULL,progress BIGINT NOT NULL DEFAULT 0,asset_id TEXT REFERENCES assets(id),created TEXT NOT NULL,UNIQUE(org_id,request_key));
CREATE TABLE IF NOT EXISTS audit(id BIGSERIAL PRIMARY KEY,org_id TEXT REFERENCES organizations(id),actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,created TEXT NOT NULL);

CREATE TABLE IF NOT EXISTS public_stores(org_id TEXT PRIMARY KEY REFERENCES organizations(id),slug TEXT NOT NULL UNIQUE);
 CREATE TABLE IF NOT EXISTS product_urls(product_id TEXT PRIMARY KEY REFERENCES products(id),org_id TEXT NOT NULL REFERENCES organizations(id),slug TEXT NOT NULL,UNIQUE(org_id,slug));
 CREATE TABLE IF NOT EXISTS shared_selections(code TEXT PRIMARY KEY,product_id TEXT NOT NULL REFERENCES products(id),version BIGINT NOT NULL,selection TEXT NOT NULL,created TEXT NOT NULL,UNIQUE(product_id,version,selection));
CREATE TABLE IF NOT EXISTS print_assets(ref TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), org_id TEXT NOT NULL REFERENCES organizations(id), name TEXT NOT NULL, mime TEXT NOT NULL, bytes BYTEA NOT NULL, width BIGINT NOT NULL, height BIGINT NOT NULL, sha256 TEXT NOT NULL, created TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_proofs(order_id TEXT NOT NULL REFERENCES orders(id),revision BIGINT NOT NULL,digest TEXT NOT NULL,note TEXT NOT NULL,requested_by TEXT NOT NULL,requested_at TEXT NOT NULL,approved_by TEXT,approved_at TEXT,PRIMARY KEY(order_id,revision));
CREATE TABLE IF NOT EXISTS commerce_tickets(id TEXT PRIMARY KEY,org_id TEXT NOT NULL REFERENCES organizations(id),product_id TEXT NOT NULL REFERENCES products(id),version BIGINT NOT NULL,selection TEXT NOT NULL,amount BIGINT NOT NULL,expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS email_verified(user_id TEXT PRIMARY KEY REFERENCES users(id),verified_at TEXT NOT NULL);
  CREATE TABLE IF NOT EXISTS email_verifications(token TEXT PRIMARY KEY,user_id TEXT NOT NULL REFERENCES users(id),expires BIGINT NOT NULL);
ALTER TABLE products ADD COLUMN IF NOT EXISTS deleted_at TEXT;
CREATE TABLE IF NOT EXISTS yenze_migrations(version INTEGER PRIMARY KEY, applied_at TIMESTAMPTZ NOT NULL DEFAULT now());
INSERT INTO yenze_migrations(version) VALUES(1) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY,hits BIGINT NOT NULL,expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS rate_limits_expiry ON rate_limits(expires);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS assets_org ON assets(org_id);
CREATE INDEX IF NOT EXISTS products_org ON products(org_id);
CREATE INDEX IF NOT EXISTS orders_org ON orders(org_id);
CREATE INDEX IF NOT EXISTS orders_user ON orders(user_id);
CREATE INDEX IF NOT EXISTS configurations_user ON configurations(user_id);
CREATE INDEX IF NOT EXISTS print_assets_product ON print_assets(product_id);
CREATE INDEX IF NOT EXISTS audit_org ON audit(org_id);
